import type { Metadata } from 'next'
import { Inter, Oswald, Quicksand, DM_Sans } from 'next/font/google'
import './globals.css'
import Header from '@/components/organisms/header'
import SessionAuthProvider from '@/context/SessionAuthProvider'

const inter = Inter({ subsets: ['latin'] })

const oswald = Oswald({ subsets: ['latin'], variable: '--font-oswald' })
const quicksand = Quicksand({
  subsets: ['latin'],
  variable: '--font-quicksand'
})
const dmsans = DM_Sans({
  subsets: ['latin'],
  variable: '--font-dmsans'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${oswald.variable} ${quicksand.variable} ${dmsans.variable} `}
      >
        <SessionAuthProvider>
          <Header />
          {children}
        </SessionAuthProvider>
      </body>
    </html>
  )
}
